spring.application.name=Infi_Payment_System

spring.datasource.url=jdbc:mysql://localhost:3306/infi_payment_system
spring.datasource.username=root
spring.datasource.password=Gopi@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=ThisIsMyVerySecureSecretKeyForJwtAuthentication123456
jwt.expiration=86400000

logging.level.root=INFO
logging.level.org.edu.infi_payment_system=DEBUG

spring.kafka.bootstrap-servers=localhost:9092

spring.data.redis.host = localhost
spring.data.redis.port = 6379