package org.edu.infi_payment_system.Audit.enums;

public enum AuditAction {
    PAYMENT_CREATED,
    PAYMENT_INITIATED,
    PAYMENT_PENDING,
    TRANSACTION_CREATED,
    INSUFFICIENT_BALANCE,
    ACCOUNT_LOCKED,
    DEBIT_SUCCESS,
    CREDIT_SUCCESS,
    LEDGER_ENTRY_COMPLETED,
    TRANSACTION_SUCCESS,
    PAYMENT_FAILED,
    FRAUD_DETECTED,
    PAYMENT_SUCCESS,
    PAYMENT_COMPLETED
}
